fix hunyuan魔改模型，fc层量化的weight的size问题
Co-authored-by: xuzhenqiang<xuzhenqiang3@huawei.com>



# message auto-generated for no-merge-commit merge:
!376 merge dev into dev

fix hunyuan魔改模型，fc层量化的weight的size问题

Created-by: zqxu
Commit-by: xuzhenqiang
Merged-by: ascend-robot
Description: <!--
PR描述模板更新日期：20251224
-->

# Which issue(s) this PR fixes or accomplishes
> **如问题已解决，按照下方示例附上ISSUE单号 / Apply bug or request issue as follow if the solved**\
Fixes #195
> **Fixes关键字会自动关闭issue，如问题部分解决请不要使用Fixes，可以用下方标签替代\
> Fixes will automatically close issue, please use the following tag if only part of the issue is solved**\
> Fix part of #ISSUE ID


# Purpose
  File "/home/miniconda3/envs/xzq_mindiesd/lib/python3.11/site-packages/mindiesd/quantization/layer.py", line 703, in _init_dynamic_quant_param
    weight_scale = weight_scale.reshape(weight_scale.shape[0], -1, 2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[4608, -1, 2]' is invalid for input of size 1783296
在加载hunyuan魔改的量化权重时候，会报这个问题，改pr是为了解决这个问题

# Test Plan
> 设计了哪些测试内容，指导他人如何对你的PR进行测试\
> Apply information to show others your test design and how to test your Pull Request


# Test Report

模型跑通的日志
root@localhost:/home/x00906174/hunyuanvideo_magic# bash single.bash
[W624 15:28:55.155814029 OptionRegister.cpp:95] Warning: Current device only support allow_internal_format=False, the requested value True is invalid and has been reverted to False. (function operator())
/usr/local/python3.11.10/lib/python3.11/site-packages/torch_npu/contrib/transfer_to_npu.py:379: ImportWarning:
    *************************************************************************************************************
    The torch.Tensor.cuda and torch.nn.Module.cuda are replaced with torch.Tensor.npu and torch.nn.Module.npu now..
    The torch.cuda.DoubleTensor is replaced with torch.npu.FloatTensor cause the double type is not supported now..
    The backend in torch.distributed.init_process_group set to hccl now..
    The torch.cuda.* and torch.cuda.amp.* are replaced with torch.npu.* and torch.npu.amp.* now..
    The device parameters have been replaced with npu in the function below:
    torch.logspace, torch.randint, torch.hann_window, torch.rand, torch.full_like, torch.ones_like, torch.rand_like, torch.randperm, torch.arange, torch.frombuffer, torch.normal, torch._empty_per_channel_affine_quantized, torch.empty_strided, torch.empty_like, torch.scalar_tensor, torch.tril_indices, torch.bartlett_window, torch.ones, torch.sparse_coo_tensor, torch.randn, torch.kaiser_window, torch.tensor, torch.triu_indices, torch.as_tensor, torch.zeros, torch.randint_like, torch.full, torch.eye, torch._sparse_csr_tensor_unsafe, torch.empty, torch._sparse_coo_tensor_unsafe, torch.blackman_window, torch.zeros_like, torch.range, torch.sparse_csr_tensor, torch.randn_like, torch.from_file, torch._cudnn_init_dropout_state, torch._empty_affine_quantized, torch.linspace, torch.hamming_window, torch.empty_quantized, torch._pin_memory, torch.load, torch.set_default_device, torch.get_device_module, torch.sparse_compressed_tensor, torch.Tensor.new_empty, torch.Tensor.new_empty_strided, torch.Tensor.new_full, torch.Tensor.new_ones, torch.Tensor.new_tensor, torch.Tensor.new_zeros, torch.Tensor.to, torch.Tensor.pin_memory, torch.nn.Module.to, torch.nn.Module.to_empty
    *************************************************************************************************************

  warnings.warn(msg, ImportWarning)
/usr/local/python3.11.10/lib/python3.11/site-packages/torch_npu/contrib/transfer_to_npu.py:300: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
2026-06-24 15:28:57.531 | INFO     | hyvideo.inference:from_pretrained:326 - Building model...
2026-06-24 15:30:10.610 | INFO     | hyvideo.vae:load_vae:53 - VAE to dtype: torch.bfloat16
2026-06-24 15:30:10.682 | INFO     | __main__:main:37 - Loading quantized model from: /mnt/weight/A5-weights/hunyuan_magic_w8a8f8_mod_bf16rot/quant_model_description_w8a8_mxfp8.json
2026-06-24 15:30:10.684 | INFO     | __main__:main:38 - Quant model device: npu:0
2026-06-24 15:30:42.047 | INFO     | __main__:main:49 - Quantized model loaded successfully
Warm up...
  0%|                                                                                                                                                                | 0/2 [00:00<?, ?it/s][W624 15:30:42.977346898 TensorFactories.cpp:423] Warning: Cannot create tensor with interal format while allow_internel_format=False, tensor will be created with base format. (function operator())
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:12<00:00,  6.42s/it]



See merge request: Ascend/MindIE-SD!376